ci:
  collect:
    numberOfRuns: 3
    settings:
      preset: desktop
      chromeFlags: '--no-sandbox'
    startServerCommand: 'yarn start'
    url:
      - http://localhost:3000

  assert:
    preset: lighthouse:no-pwa
    assertions:
      csp-xss: off # https://github.com/tonychristopherofficial/tonychristopherofficial.com#%EF%B8%8F-todo
      bf-cache: off # no needed
      non-composited-animations: warn
      unminified-css: warn
      unused-css-rules: warn
      unused-javascript: warn
      uses-responsive-images: warn
      uses-text-compression: warn # I don't know why it's failed, but the results aren't failed.
